server:
  port: 8084
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus
          temperature: 0.7
    mcp:
      client:
        sse:
          connections:
            ai-spring:
              url: http://localhost:8083
