spring:
  profiles:
    active: dev

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://test.toutiao.im:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: demo-zuul
  profiles: test

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: demo-zuul
  profiles: dev

zuul:
  routes:
    demo:
      path: /demo/**
      serviceId: demo-consumer
      stripPrefix: true
      sensitiveHeaders: // 表示不过滤Headers，如Cookie
    demo2:
      path: /demo2/**
      serviceId: demo2-consumer
      stripPrefix: true